[theme]
primaryColor = "#ffe17c"
backgroundColor = "#171e19"
secondaryBackgroundColor = "#272727"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "info"

[server]
headless = true
port = 8501
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[ui]
hideTopBar = false
hideFooterIcons = false
